# Generated by Django 4.2.7 on 2023-11-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_cat", models.CharField(max_length=100)),
                ("date_added_cat", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_added_cat"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_prod", models.CharField(max_length=150)),
                ("price_prod", models.FloatField()),
                ("description_prod", models.TextField()),
                ("image_prod", models.CharField(max_length=500)),
                ("date_added_prod", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cat_prod_id",
                        to="myShop.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added_prod"],
            },
        ),
    ]
