# Generated by Django 4.2.7 on 2023-12-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myShop", "0002_commande"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="prix",
            field=models.FloatField(null=True),
        ),
    ]
